"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const ideas = [
  { rank: 1, title: "OnceDE Family Start", score: 93, tag: "RECOMMENDED", problem: "Families repeatedly submit the same information across fragmented public-service journeys, with little visibility into data use or application status.", solution: "A multilingual, consent-first layer that requests only necessary evidence, prefills forms, records every access and keeps human support reachable.", demo: "/once-only", strengths: ["Fits digital inclusion + smarter services", "Concrete fictional-data demo exists", "Clear field-test group: families + advice centers", "Strong Germany–Estonia–Taiwan learning story"], measure: "Time saved · duplicate fields avoided · comprehension · completed next steps" },
  { rank: 2, title: "Gemeinsam Berlin", score: 86, tag: "DEMOCRACY TRACK", problem: "Traditional online participation rewards conflict, excludes non-German speakers and rarely creates an accountable path from input to implementation.", solution: "A multilingual statement-voting process that reveals cross-group consensus and requires a public accept/change/reject response from a partner institution.", demo: "/gemeinsam", strengths: ["Directly inspired by Taiwan", "Live multilingual voting works", "Real group-level aggregation", "Expandable to AI-supported clustering"], measure: "Participant diversity · cross-group consensus · public response · adoption" },
  { rank: 3, title: "Public Systems Lab Kit", score: 74, tag: "ECOSYSTEM", problem: "Civic-tech prototypes often disappear after hackathons because community, institutional ownership and implementation commitments are missing.", solution: "An open playbook and prototype hub for recurring public problem labs: nominate, diagnose, deliberate, build, field-test and document adoption.", demo: "/projects", strengths: ["Scalable community infrastructure", "Connects Code for Germany and g0v patterns", "Creates reusable public digital assets", "Strong long-term vision"], measure: "Problems nominated · prototypes field-tested · partners committed · projects reused" },
];

export default function HackathonPage() {
  const [selected, setSelected] = useState(1);
  useEffect(() => { navigator.sendBeacon("/api/event", new Blob([JSON.stringify({ event: "hackathon_view", detail: "taiwan-2026" })], { type: "application/json" })); }, []);
  const idea = ideas.find(item => item.rank === selected) ?? ideas[0];
  return <main className="hack-page">
    <header className="hack-header"><Link href="/hackathon" className="wordmark">BERLIN ↔ TAIWAN</Link><span>2026 PRESIDENTIAL HACKATHON</span><Link href="/projects">Prototype Library ↗</Link></header>
    <section className="hack-hero"><p className="eyebrow">International Track · Digital Inclusion in the AI Era</p><h1>Don’t submit an idea.<br/><em>Submit a learning system.</em></h1><div><p>Unsere stärkste Einreichung verbindet eine funktionierende Demo, eine reale Zielgruppe und ein überprüfbares Feldexperiment. Deadline: 31 July 2026.</p><a href="https://presidential-hackathon.taiwan.gov.tw/en/international-track/" target="_blank" rel="noreferrer">Official call ↗</a></div></section>
    <section className="idea-rank"><div className="section-heading"><p className="eyebrow">Ranked for fit × evidence × feasibility</p><h2>Drei mögliche Einreichungen.</h2></div><div className="idea-tabs">{ideas.map(item => <button className={selected === item.rank ? "active" : ""} onClick={() => setSelected(item.rank)} key={item.rank}><span>0{item.rank}</span><div><b>{item.title}</b><small>{item.tag}</small></div><strong>{item.score}/100</strong></button>)}</div>
      <article className="pitch-card"><div className="pitch-score"><span>FIT SCORE</span><b>{idea.score}</b><small>/ 100</small></div><div className="pitch-main"><span>{idea.tag}</span><h2>{idea.title}</h2><div className="pitch-columns"><div><small>PUBLIC PROBLEM</small><p>{idea.problem}</p></div><div><small>PROPOSED SOLUTION</small><p>{idea.solution}</p></div></div><ul>{idea.strengths.map(strength => <li key={strength}>✓ {strength}</li>)}</ul><div className="measure"><small>QUANTIFIABLE BENEFIT</small><p>{idea.measure}</p></div><Link href={idea.demo}>Working demo öffnen →</Link></div></article>
    </section>
    <section className="recommendation"><div><p className="eyebrow">My recommendation</p><h2>Submit OnceDE. Use Gemeinsam Berlin as proof of the wider lab.</h2></div><div><p><b>Warum:</b> OnceDE löst einen klaren, universellen Zugangsengpass und passt unmittelbar zu „Digital Inclusion“ und „Smarter Services“. Die Demo zeigt bereits Einwilligung, Vorausfüllung, Widerruf und Auditierbarkeit.</p><p>Gemeinsam Berlin stärkt die Bewerbung als zweites Beweisstück: Wir bauen nicht nur Service-Interfaces, sondern Beteiligungsprozesse, durch die betroffene Menschen die Anforderungen mitgestalten.</p></div></section>
    <section className="submission-map"><div className="section-heading"><p className="eyebrow">Application map</p><h2>Was bis zur Einreichung fehlt.</h2></div><div className="check-grid"><article><span>01</span><h3>Team · 3–10 people</h3><p>Michael: product/system design. Dazu eine Person aus Beratung oder Verwaltung und eine technische beziehungsweise Research-Perspektive.</p><b>OPEN</b></article><article><span>02</span><h3>Field validation</h3><p>Fünf Familien und eine Beratungsstelle testen Verständnis, Einwilligung und vorausgefüllte Schritte.</p><b>OPEN</b></article><article><span>03</span><h3>English submission</h3><p>Problem, stakeholders, functions, difference, SDGs, maturity, measurable benefit and demo link.</p><b>READY TO DRAFT</b></article><article><span>04</span><h3>Originality & rights</h3><p>Team agreement festhalten. Bestehende Komponenten und Lizenzen dokumentieren. Keine echten personenbezogenen Daten einreichen.</p><b>REQUIRED</b></article></div></section>
    <section className="ethics-panel"><div><p className="eyebrow">Competition consent · practical reading</p><h2>Was du mit der Anmeldung akzeptierst.</h2></div><ul><li>Die Organisatoren erfassen umfangreiche persönliche und berufliche Daten der Teammitglieder.</li><li>Dein Team behält grundsätzlich die Rechte am Beitrag, räumt den Organisatoren aber eine kostenlose Nutzung der eingereichten Materialien für nichtkommerzielle Projektzwecke ein.</li><li>Teaminterne Rechte und Verantwortlichkeiten müssen vorab schriftlich geklärt werden.</li><li>Weitergekommene Teams müssen an Mentoring, Präsentationen, Promotion und Follow-up teilnehmen.</li><li>Für unseren Demo- und Feldtest verwenden wir keine Pass-, Register- oder sensiblen Familiendaten.</li></ul></section>
    <section className="team-call"><p className="eyebrow">Build the bridge</p><h2>Gesucht: Praxispartner:in und Teammitglied.</h2><p>Bildungs- oder Sozialberatung, Verwaltung, Civic Tech, Datenschutz oder partizipative Forschung. Ein begrenzter Pilot, offene Ergebnisse, keine Datenverwertung.</p><Link href="/#interest">Interesse senden →</Link></section>
    <footer><Link className="wordmark" href="/hackathon">BERLIN ↔ TAIWAN</Link><p>Human Systems Lab · Submission workspace</p><Link href="/gemeinsam">Gemeinsam Berlin</Link></footer>
  </main>;
}
